---

- name: Add key for webupd8 repository
  apt_key: keyserver=keyserver.ubuntu.com id=EEA14886 state=present

- name: Add webupd8 repository
  #apt_repository: repo='deb http://ppa.launchpad.net/webupd8team/java/ubuntu lucid main' state=present
  #apt_repository: repo='deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main' state=present
  apt_repository: repo='deb http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main' state=present

- name: Accept Oracle Java license
  debconf: name='oracle-java7-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: Update repository cache
  apt: update_cache=yes

- name: Install Java8
  #apt: name=oracle-java8-installer=8u45+8u33arm-1~webupd8~0 state=present
  apt: name=oracle-java8-installer state=latest

- name: Set Java8 env
  apt: name=oracle-java8-set-default state=latest

- name: Set /dev/urandom as source
  lineinfile: dest=/usr/lib/jvm/java-8-oracle/jre/lib/security/java.security regexp="^securerandom\.source=" line="securerandom.source=file:/dev/urandom" state=present

