---

- name: Check if VM is already running
  shell: virsh list | grep " {{inventory_hostname}} "
  register: vm_running_result
  failed_when: vm_running_result.rc != 0 and vm_running_result.rc != 1
  changed_when: vm_running_result.rc != 0
  delegate_to: "{{hypervisor}}"
  
- name: Start VMs
  command: virsh start {{inventory_hostname}}
  when: vm_running_result.rc == 1
  delegate_to: "{{hypervisor}}"

