---

- name: Install KVM packages
  apt: name={{item}} state=present
  with_items:
    - qemu-kvm
    - libvirt-bin
#    - virtinst

- name: Enable nested virtualization
  copy: src=nested-virtualization.conf dest=/etc/modprobe.d/nested-virtualization.conf
  notify:
    - reload kvm_intel

