---
- hosts: l1kvmhosts
  gather_facts: False
  serial: 1
  roles:
    - { role: kvmguest, tags: ['kvm'] }

- hosts: l1kvmhosts
  gather_facts: True
  serial: 1
  roles:
    - { role: kvmhost, tags: ['kvm'] }

