---

- hosts: rootservers
  tasks:
    - name: Check if LUKS device is already opened
      shell: cryptsetup status {{crypt_name}} | grep "is active"
      register: luks_open_result
      failed_when: luks_open_result.rc != 0 and luks_open_result.rc != 1
      changed_when: luks_open_result.rc != 0

    - name: Copy passphrase
      copy: content="{{luks_pass}}" dest=/root/.luks_pass_tmp
      when: luks_open_result.rc == 1

    - name: Open LUKS device
      shell: cat /root/.luks_pass_tmp | cryptsetup luksOpen {{crypt_dev}} {{crypt_name}}
      when: luks_open_result.rc == 1

    - name: Delete passphrase
      command: shred -z -u /root/.luks_pass_tmp
      when: luks_open_result.rc == 1

    #- name: Create crypted volumne group
    #  lvg: vg={{crypt_vg}} pvs={{crypt_mapping}} state=present
    - name: Activate volume group
      command: vgchange -a y {{crypt_vg}}

- hosts: kvm-guests
  gather_facts: False
  tasks:
    - name: Check if VM is already running
      shell: virsh list | grep " {{inventory_hostname}} "
      register: vm_running_result
      failed_when: vm_running_result.rc != 0 and vm_running_result.rc != 1
      changed_when: vm_running_result.rc != 0
      delegate_to: "{{hypervisor}}"
      
    - name: Start VMs
      command: virsh start {{inventory_hostname}}
      when: vm_running_result.rc == 1
      delegate_to: "{{hypervisor}}"

