---

- name: Install Munin dependencies for Nginx
  apt: name=libwww-perl state=present

- name: Enable Munin Nginx plugin
  file:
    src: /usr/share/munin/plugins/{{item}}
    dest: /etc/munin/plugins/{{item}}
    state: link
  with_items:
    - nginx_request
    - nginx_status
  notify:
    - Restart munin-node

