---

- name: Install packages
  apt: name={{item}} state=present
  with_items:
    - munin-node

- name: Copy munin-node config
  template:
    src: munin-node.conf.j2
    dest: /etc/munin/munin-node.conf
  notify:
    - Restart munin-node

- name: Allow connection to munin port 4949
  ufw:
    rule: allow
    port: 4949
    src: "{{hostvars[munin.master].network.ipv6.address}}"
    proto: tcp
  notify:
    - Reload ufw

- name: Get installed packages
  shell: dpkg-query -f '${binary:Package}\n' -W
  register: packages
  changed_when: False

- include_tasks: _apache2.yml
  when: '"apache2" in packages.stdout_lines'

- include_tasks: _nginx.yml
  when: '"nginx" in packages.stdout_lines'

- include_tasks: _mysql.yml
  when: '"mariadb-server" in packages.stdout_lines'

- include_tasks: _postgresql.yml
  when: '"postgresql" in packages.stdout_lines'

- include_tasks: _slapd.yml
  when: '"slapd" in packages.stdout_lines'

- include_tasks: _munin.yml
  when: '"munin" in packages.stdout_lines'

- include_tasks: _java.yml
  when: '"openjdk-8-jre:amd64" in packages.stdout_lines'

