vm:
    ram: 4096
    cpus: 4
    disk: 100
    mirror:
        hostname: mirror.hetzner.de
        directory: /ubuntu/packages
    distro:
        location: http://de.archive.ubuntu.com/ubuntu/dists/trusty/main/installer-amd64/

