---

- name: Open crypt device (crypt)
  include_tasks: _open-luks.yml
  when: crypt is defined

- name: Open crypt device (storage.crypt)
  include_tasks: _open-luks.yml
  when: storage is defined and storage.crypt is defined
  vars:
    crypt: '{{storage.crypt}}'

- name: Open crypt device (storage.storagebox.crypt)
  include_tasks: _open-luks.yml
  when: storage is defined and storage.storagebox is defined and storage.storagebox.crypt is defined
  vars:
    crypt: '{{storage.storagebox.crypt}}'

