---

- name: Delete nixconreg git repo
  become_user: nixconreg
  file:
    path: /tmp/nixconreg
    state: absent

- name: Create nixconreg git repo
  become_user: nixconreg
  file:
    path: /tmp/nixconreg
    state: directory

- name: Archive nixconreg git repo
  local_action: archive path="{{ nixconreg.gitsrc }}" dest="/tmp/nixconreg.zip" format="zip"

- name: Copy nixconreg git repo
  become_user: nixconreg
  unarchive:
    src: /tmp/nixconreg.zip
    dest: /tmp/nixconreg

- name: Clone/update git repository
  become_user: nixconreg
  git:
    repo: /tmp/nixconreg
    dest: /var/www/nixconreg
    force: yes

- name: Setup settings
  become_user: nixconreg
  file:
    src: /var/www/nixconreg/registration/settings-prod.py
    dest: /var/www/nixconreg/registration/settings.py
    owner: nixconreg
    group: www-data
    state: link

- name: Setup virtualenv
  become_user: nixconreg
  pip:
    virtualenv: /var/www/nixconreg/venv
    state: latest
    virtualenv_command: pyvenv-3.4
    name: /var/www/nixconreg/registration/
    extra_args: "--download-cache /var/cache/nixconreg/pip"

- name: Migrate database
  become_user: nixconreg
  shell: /var/www/nixconreg/venv/bin/python3 manage.py db upgrade
  args:
    chdir: /var/www/nixconreg

- name: Touch WSGI
  become_user: nixconreg
  file:
    path: /var/www/nixconreg/registration.wsgi
    state: touch

