---

- name: Install packages
  apt: name={{item}} state=present
  with_items:
    - python3
    - python3-pip
    - python3-virtualenv
    - python3-venv
    - python3-dev
    - python3-setuptools
    - apache2
    - sqlite3
    - libapache2-mod-wsgi-py3
    - git

- name: Enable Apache modules
  apache2_module: name={{item}} state=present
  notify:
    - Restart apache2
  with_items:
    - rewrite
    - proxy
    - proxy_http
    - ssl
    - expires
    - headers

- name: Create nixconreg user
  user:
    name: nixconreg
    group: www-data

- name: Create nixconreg www folder
  file:
    path: /var/www/nixconreg
    state: directory
    mode: 0755
    owner: nixconreg
    group: www-data

- name: Create nixconreg log folder
  file:
    path: /var/log/nixconreg
    state: directory
    mode: 0755
    owner: nixconreg
    group: www-data

- name: Create nixconreg pip cache folder
  file:
    path: /var/cache/nixconreg/pip
    state: directory
    mode: 0755
    owner: nixconreg
    group: www-data

- name: Copy nixconreg conf
  copy:
    src: nixconreg.conf
    dest: /etc/apache2/conf-enabled/nixconreg.conf
  notify:
    - Restart apache2

- name: Deploy
  tags: deploy
  include: _deploy.yml

