---

- name: Manage builtins
  lineinfile:
    dest: /etc/default/ufw
    regexp: "^MANAGE_BUILTINS="
    line: "MANAGE_BUILTINS=yes"
  notify:
    - Reload ufw

- name: Copy nat rules
  template:
    src: "{{item}}.j2"
    dest: "/etc/ufw/{{item}}"
  with_items:
    - nat4

- name: Register nat rules
  shell: "cat /etc/ufw/{{item.snippet}}"
  register: nat
  with_items:
    - rule: before
      snippet: nat4

#- name: Debug
#  debug: var=nat.results

- name: Put nat rules into before.rules
  blockinfile:
    dest: /etc/ufw/{{item.item.rule}}.rules
    block: "{{item.stdout}}"
    insertbefore: "# Don't delete these required lines"
  with_items: "{{nat.results}}"
  notify:
    - Reload ufw

