---

- name: Install ufw
  apt:
    name: ['ufw']
    state: present

- name: Allow ssh traffic
  ufw: rule=limit port=ssh proto=tcp

- name: Enable logging
  ufw: logging=on

- name: Enable ufw
  ufw: state=enabled

- import_tasks: _forward.yml
  when: firewall is defined and ( firewall.forward is defined or firewall.nat is defined )

- import_tasks: _nats.yml
  when: firewall is defined and firewall.nat is defined

- import_tasks: _rules.yml
  when: firewall is defined and firewall.rules is defined

- meta: flush_handlers

