---

- name: Clone/update git repository
  become_user: techism
  git:
    repo: https://github.com/techism/techism.git
    dest: /var/www/techism
    force: yes

- name: Setup virtualenv
  become_user: techism
  pip:
    virtualenv: /var/www/techism/venv
    requirements: /var/www/techism/dependencies.pip
    virtualenv_site_packages: yes
    extra_args: "--download-cache /var/cache/techism/pip"

- name: Update settings
  become_user: techism
  lineinfile:
    dest: /var/www/techism/techism/settings/server.py
    regexp: "{{item.regexp}}"
    line: "{{item.line}}"
  with_items:
    - regexp: "^EMAIL_SUBJECT_PREFIX"
      line: "EMAIL_SUBJECT_PREFIX = '{{techism.email_subject_prefix}} '"
    - regexp: "^ALLOWED_HOSTS"
      line: "ALLOWED_HOSTS = ['{{fqdn}}']"
    - regexp: "^HTTP_URL"
      line: "HTTP_URL = 'http://{{fqdn}}'"
    - regexp: "^HTTPS_URL"
      line: "HTTPS_URL = 'https://{{fqdn}}'"

- name: Migrate database
  become_user: techism
  django_manage:
    command: migrate
    app_path: /var/www/techism
    virtualenv: /var/www/techism/venv
    settings: techism.settings.server

- name: Collect static resources
  become_user: techism
  django_manage:
    command: collectstatic
    app_path: /var/www/techism
    virtualenv: /var/www/techism/venv
    settings: techism.settings.server

#- name: Run tests
#  become_user: techism
#  django_manage:
#    command: test
#    apps: techism
#    app_path: /var/www/techism
#    virtualenv: /var/www/techism/venv
#    settings: techism.settings.server

- name: Touch WSGI
  become_user: techism
  file:
    path: /var/www/techism/techism/settings/server_wsgi.py
    state: touch

- name: Enable crontab
  become_user: techism
  shell: "crontab < /var/www/techism/conf/crontab"
  when: fqdn == "www.techism.de"

