---

- name: Create user
  user:
    name: "{{item.name}}"
    createhome: yes
    shell: /bin/bash
  with_items:
    - "{{users}}"

- name: Set authorized key
  authorized_key:
    user: "{{item.name}}"
    key: "{{item.authorized_key}}"
    state: present
  with_items:
    - "{{users}}"

- name: Add user to sudo group
  user:
    name: "{{item.name}}"
    groups: sudo
    append: yes
  with_items:
    - "{{users}}"
  when: item.sudo

- name: Enable passwordless sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: "^{{item.name}} "
    line: "{{item.name}} ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"
  with_items:
    - "{{users}}"
  when: item.sudo

