---

- name: Add Jenkins apt repository key
  apt_key:
    url: http://pkg.jenkins.io/debian/jenkins.io.key
    state: present

- name: Add Jenkins apt repository
  apt_repository:
    repo: deb http://pkg.jenkins.io/debian binary/
    state: present
    update_cache: yes

- name: Install Jenkins and Tools
  apt: name={{item}} state=present
  with_items:
    - curl
    - jenkins
    - xvfb
    - iceweasel
    - rpm

- name: Limit heap
  lineinfile:
    path: /etc/default/jenkins
    state: present
    regexp: '^JAVA_ARGS='
    line: 'JAVA_ARGS="-Xmx512m -Djava.awt.headless=true"'
  notify: Restart jenkins

- name: Copy config
  copy:
    src: "{{item}}"
    dest: /var/lib/jenkins/{{item}}
    owner: jenkins
    group: jenkins
    mode: 0644
  with_items:
    - config.xml
    - hudson.tasks.Maven.xml
    - org.jenkinsci.plugins.xvfb.Xvfb.xml
  notify: Restart jenkins
  # TODO: must restart Jenkins immediately if config.xml changed

- name: Create seed job directory
  file:
    path: /var/lib/jenkins/jobs/seed 
    state: directory
    owner: jenkins
    group: jenkins
    mode: 0755
  notify: Restart jenkins

- name: Copy seed job
  copy:
    src: seed.xml
    dest: /var/lib/jenkins/jobs/seed/config.xml
    owner: jenkins
    group: jenkins
    mode: 0644
  notify: Restart jenkins

- name: Download jenkins-cli.jar
  get_url:
    url: http://localhost:8080/jnlpJars/jenkins-cli.jar
    dest: /tmp/jenkins-cli.jar

- name: Install Jenkins plugins
  shell: java -jar /tmp/jenkins-cli.jar -s http://localhost:8080/ install-plugin {{ item }}
    creates=/var/lib/jenkins/plugins/{{ item }}.jpi
  with_items:
    - subversion
    - git
    - github
    - git-client
    - scm-api
    - job-dsl
    - xvfb
    - ws-cleanup
    - maven-plugin
    - metrics
    - build-timeout
    - pipeline-model-definition
    - pipeline-maven
  notify: Restart jenkins

- name: Update Jenkins plugins
  shell: "java -jar /tmp/jenkins-cli.jar -s http://localhost:8080/ list-plugins | cut -d' ' -f1 | xargs java -jar /tmp/jenkins-cli.jar -s http://localhost:8080/ install-plugin"

- name: Enable tmpfs
  service:
    name: tmp.mount
    enabled: yes
    state: started

- name: Add jenkins user to docker group
  user:
    name: jenkins
    groups: docker
    append: yes
  notify: Restart jenkins

