---

- hosts: all
  gather_facts: False
  roles: 
    - role: assert-single-host
    - role: reboot

- hosts: all
  gather_facts: False
  vars:
    ansible_become: no
  roles: 
    - role: assert-single-host
    - { role: ssh-tools, down: True, clean: False, up: True }

