---

- name: Install packages
  apt: name={{item}} state=present
  with_items:
    - request-tracker4
    - rt4-db-sqlite
    - sqlite3
    - rt4-clients
    - rt4-apache2
    - apache2
    - msmtp
    - fetchmail
    - vim

- name: Enable Apache modules
  apache2_module: name={{item}} state=present
  notify:
    - Restart apache2
  with_items:
    - rewrite
    - perl

- name: Enable RT Apache config
  file:
    src: /etc/request-tracker4/apache2-modperl2.conf
    dest: /etc/apache2/conf-enabled/apache2-modperl2.conf
    state: link
  notify:
    - Restart apache2

- name: Configure RT
  template:
    src: 99-config.j2
    dest: /etc/request-tracker4/RT_SiteConfig.d/99-config
    owner: root
    group: root
    mode: 0600
  notify:
    - Run update-rt-siteconfig-4
    - Restart apache2

- name: Configure msmtp
  template:
    src: msmtp_wrapper.conf.j2
    dest: /etc/request-tracker4/msmtp_wrapper.conf
    owner: www-data
    group: www-data
    mode: 0600

- name: Create msmtp wrapper
  template:
    src: msmtp_wrapper.j2
    dest: /etc/request-tracker4/msmtp_wrapper
    owner: www-data
    group: www-data
    mode: 0700

- name: Create msmtp log file
  file:
    path: /var/log/msmtp.log
    owner: www-data
    group: www-data
    mode: 0664
    state: touch

- name: Configure fetchmail
  template:
    src: fetchmailrc.j2
    dest: /etc/fetchmailrc
    owner: fetchmail
    group: root
    mode: 0600
  notify:
    - Restart fetchmail

- name: Enable fetchmail
  lineinfile:
    dest: /etc/default/fetchmail
    regexp: "^START_DAEMON="
    line: "START_DAEMON=yes"
  notify:
    - Restart fetchmail

