---

- name: Install base packages
  apt: name={{item}} state=present
  with_items:
    - python
    - python-apt
    - sudo
    - vim
    - tmux
    - git
    - tree
    - traceroute
    - iputils-ping

