---

- name: Create admin users
  user: >
    name={{item.username}}
    password={{item.password}}
    groups=sudo
    shell=/bin/bash
    createhome=yes
    state=present
  with_items: admins

- name: Set authorized keys
  authorized_key: >
    user="{{item.0.username}}"
    key="{{item.1}}"
    state=present
  with_subelements:
    - admins
    - ssh_public_keys

- name: Disallow password authentication
  lineinfile: >
    dest=/etc/ssh/sshd_config
    regexp="^PasswordAuthentication"
    line="PasswordAuthentication no"
    state=present

- name: Disallow root login
  lineinfile: >
    dest=/etc/ssh/sshd_config
    regexp="^PermitRootLogin"
    line="PermitRootLogin no"
    state=present

