---

- name: Install packages
  apt: name={{item}} state=present
  with_items:
    - openssl
    - ca-certificates
    - ssl-cert

- name: Set fqdns
  set_fact:
    fqdns: "{{ [fqdn] + fqdn_aliases|default([]) }}"

- name: Slurp private key
  slurp: src=/etc/ssl/private/{{item}}.key
  register: ssl_key
  delegate_to: "{{ipv4gw}}"
  with_items: "{{fqdns}}"

- name: Write private key
  copy:
    dest: /etc/ssl/private/{{item.item}}.key
    content: "{{ item.content | b64decode }}"
    mode: 0640
    owner: root
    group: ssl-cert
  no_log: True
  with_items: "{{ssl_key.results}}"

- name: Slurp certificate
  slurp: src=/etc/ssl/certs/{{item}}.crt
  register: ssl_crt
  delegate_to: "{{ipv4gw}}"
  with_items: "{{fqdns}}"

- name: Write certificate
  copy:
    dest: /etc/ssl/certs/{{item.item}}.crt
    content: "{{ item.content | b64decode }}"
    mode: 0644
  no_log: True
  with_items: "{{ssl_crt.results}}"

- name: Register services
  shell: "systemctl status {{item}}"
  register: services
  with_items:
    - nginx
    - apache2
    - slapd
  failed_when: False

#- name: Debug
#  debug: var=services.results

- name: Restart services
  service: name={{item.item}} state=restarted
  with_items: "{{services.results}}"
  when: item.rc == 0

