---

- name: Install packages
  apt: name={{item}} state=present
  with_items:
    - openssl
    - ca-certificates
    - ssl-cert

- name: Slurp private key
  slurp: src=/etc/ssl/private/{{fqdn}}.key
  register: ssl_key
  delegate_to: "{{ipv4gw}}"

- name: Write private key
  copy:
    dest: /etc/ssl/private/{{fqdn}}.key
    content: "{{ ssl_key.content | b64decode }}"
    mode: 0640
    owner: root
    group: ssl-cert

- name: Slurp certificate
  slurp: src=/etc/ssl/certs/{{fqdn}}.crt
  register: ssl_crt
  delegate_to: "{{ipv4gw}}"

- name: Write certificate
  copy:
    dest: /etc/ssl/certs/{{fqdn}}.crt
    content: "{{ ssl_crt.content | b64decode }}"
    mode: 0644

