---

- name: Check if CSR file exists
  stat: path={{letsencrypt_csr_file}}
  register: csr

- name: Generate CSR
  shell: "openssl req -new -sha256 -key {{letsencrypt_key_file}} -subj '/CN={{letsencrypt_domain}}' > {{letsencrypt_csr_file}}"
  when: not csr.stat.exists

# View CSR:
# openssl req -in domain.csr -noout -text

