---

- set_fact:
    letsencrypt_domain: "{{letsencrypt_domain}}"
    letsencrypt_work_dir: /tmp/letsencrypt/{{letsencrypt_domain}}
    letsencrypt_webroot_dir: /tmp/letsencrypt/{{letsencrypt_domain}}/webroot
    letsencrypt_acme_dir: /tmp/letsencrypt/{{letsencrypt_domain}}/webroot/.well-known/acme-challenge
    letsencrypt_key_file: /etc/ssl/private/{{letsencrypt_domain}}.key
    letsencrypt_csr_file: /etc/ssl/private/{{letsencrypt_domain}}.csr
    letsencrypt_crt_file: /etc/ssl/certs/{{letsencrypt_domain}}.crt
    
- name: Install packages
  apt:
    name: ['python', 'openssl', 'ca-certificates', 'ssl-cert']
    state: present

- name: Check certificate status
  stat: path={{letsencrypt_crt_file}} 
  register: crt

- name: Private key
  import_tasks: _key.yml

- name: CSR
  import_tasks: _csr.yml
  
- name: Certificate
  import_tasks: _crt.yml
  when: not crt.stat.exists or crt.stat.size == 0 or ansible_date_time.epoch|float - crt.stat.mtime > 60*60*24*45

