---

- name: Install packages
  apt: name={{item}} state=present
  with_items:
    - python
    - openssl
    - ca-certificates

- name: Check certificate status
  stat: path={{letsencrypt_crt_file}} 
  register: crt

- name: Private key
  include: _key.yml

- name: CSR
  include: _csr.yml
  
- name: Certificate
  include: _crt.yml
  when: not crt.stat.exists or crt.stat.size == 0 or ansible_date_time.epoch|float - crt.stat.mtime > 60*60*24*45

