---

- name: Restart postfix
  service:
    name: postfix
    state: restarted

- name: Run postmap
  shell: postmap /etc/postfix/virtual && postmap /etc/postfix/virtual-mailbox-domains && postmap /etc/postfix/virtual-mailbox-users && newaliases

- name: Restart spamassassin
  service:
    name: '{{item}}'
    state: restarted
  with_items:
    - spamass-milter
    - spamassassin

- name: Restart dovecot
  service:
    name: dovecot
    state: restarted

